version: 0.2
eb_codebuild_settings:
    eb_codebuild_settings:
    CodeBuildServiceRole: arn:aws:codebuild:us-east-1:258412960645:project/cookin_fullstack
    ComputeType: BUILD_GENERAL1_SMALL
    Image: aws/codebuild/standard:1.0
    Timeout: 10

phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - npm run build
artifacts:
    files:
        - "./client/build"
    # base-directory: "./build"
