version: 0.2

phases:
    install:
        commands:
            - npm install
    build:
        commands:
            - cd ./client && npm install && npm run build
artifacts:
    files:
        - "**/*"
