export const GET_ALL_RECIPES = "GET_ALL_RECIPES";
export const DRAFT_RECIPE = "DRAFT_RECIPE";
export const ADD_RECIPE = "ADD_RECIPE";
export const EDIT_RECIPE = "EDIT_RECIPE";
export const GET_CURRENT_RECIPE = "GET_CURRENT_RECIPE";
export const CLEAR_CURRENT_RECIPE = "CLEAR_CURRENT_RECIPE";
export const EDIT_STATE = "EDIT_STATE";
export const RESET_RECIPE = "RESET_RECIPE";
